# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  check-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Go version from go.mod file
      id: go-version
      run: |
        version=$(awk '/^go / {print $2}' go.mod)
        echo "version=$version" >> $GITHUB_OUTPUT
    - name: Used Go version
      run: echo "Go version is ${{ steps.go-version.outputs.version }}"
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ steps.go-version.outputs.version }}'
        cache: false
        
    - name: Verify dependencies
      run: go mod verify

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

