name: Go Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Go version from go.mod file
        id: go-version
        run: |
          version=$(awk '/^go / {print $2}' go.mod)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Used Go version
        run: echo "Go version is ${{ steps.go-version.outputs.version }}"
      - uses: actions/setup-go@v5
        with:
          go-version: '${{ steps.go-version.outputs.version }}'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.0
          args: --timeout=30m --config=./.golangci.pipeline.yaml
