name: Release

on:
  push:
    tags:
      - '*'

jobs:

  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Get repository license
        id: get_license
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          license_json=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }})
          license_type=$(echo "$license_json" | jq -r '.license.key // empty')
          echo "license_type=$license_type" >> $GITHUB_OUTPUT
      - name: Use the license type
        run: echo "Repository license key is ${{ steps.get_license.outputs.license_type }}"

      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LICENSE_TYPE: ${{ steps.get_license.outputs.license_type }}
