name: Go Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache: false

      - name: golangci-lint
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.24.5
          go-package: ./...
